# Generated by Django 2.0.4 on 2018-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PRNT', 'parenting'), ('EDUC', 'education'), ('FOOD', 'food'), ('OUTD', 'outdoors')], default='PRNT', max_length=4),
            preserve_default=False,
        ),
    ]
