# Generated by Django 2.0.5 on 2018-05-03 22:14

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(default='USA', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='facilitator_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='nohta_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='participant_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='partners',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='test', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='rohta_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='sectors',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='who_jee',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='test', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='workshop',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='test', max_length=3),
        ),
    ]
